apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: YOUR-RESISTORY-NAME/node-app:latest
        ports:
        - containerPort: 8080

# hirodevops04/hello-app:latest
# gcr.io/deductive-nexus-288806/hello-app:v1
